export const CLICAR_CLEAR= 'CLICAR_CLEAR';
export const CLICAR_NUMERICO= 'CLICAR_NUMERICO';
export const CLICAR_OPERACAO= 'CLICAR_OPERACAO';
export const CLICAR_RESULTADO= 'CLICAR_RESULTADO';
export const EXIBIR_OVERFLOW= 'EXIBIR_OVERFLOW';
export const ESCONDER_OVERFLOW= 'ESCONDER_OVERFLOW';